#% text_encoding = iso8859_1
:raster_symbol_manager_gui		:en_gb	Raster Symbols Configuration
:title					:en_gb	Raster Symbols Configuration
:btn_refresh				:en_gb	Refresh
:btn_versions				:en_gb	Versions...
:btn_open				:en_gb	Open...
:btn_save				:en_gb	Save
:btn_save_as				:en_gb	Save as...
:btn_close				:en_gb	Close
:btn_help				:en_gb	Help
:btn_attach				:en_gb	Attach
:btn_detach				:en_gb	Detach
:btn_set				:en_gb	Set
:btn_clear				:en_gb	Clear
:tab_goto				:en_gb	Goto Mappings
:tab_properties				:en_gb	Symbol Properties
:tab_rwo_mappings			:en_gb	RWO Style Mappings
:tab_default_properties			:en_gb	Default Properties
:tt_new					:en_gb	New symbol from file
:tt_new_from_def			:en_gb	Create symbol from selected symbol definition
:tt_delete_sym				:en_gb	Delete selected symbol (definition)
:tt_draw_sym				:en_gb	Draw selected symbol in current map view
:tt_highlight_toggle			:en_gb	Draw in highlight?
:tt_follow_select			:en_gb	Show map selection in rwo hierarchy
:tt_option_on				:en_gb	Toggle drawing Goto symbols
:btn_module				:en_gb	Module
:btn_copy_sym				:en_gb	Copy
:btn_show_in_expl			:en_gb	Show image in Windows Explorer
:yes_message				:en_gb	Yes
:no_message				:en_gb	No
:confirm_copy				:en_gb	Do you want to copy the selected symbol to the module '#1' ?
:title_generic				:en_gb	Generic
:title_specialised			:en_gb	Specialised
:numerator				:en_gb	Numerator
:title_specific				:en_gb	Specific
:preview_too_large			:en_gb	This raster file
is
too large
to be previewed
:speed_label1				:en_gb	Speed #1 ms
:speed_label2				:en_gb	Speed (#1) #2 ms
:realise_q				:en_gb	This is an unrealised symbol definition. Do you want to create a raster symbol?
:no_sym_selected			:en_gb	No Symbol selected
:no_rwo_style_selected			:en_gb	No Style records selected
:attach_q				:en_gb	Do you want to attach the selected symbol to the #1 selected style records?
:attached_already			:en_gb	Rwo style already has a Raster Symbol custom_draw_style
:detach_q				:en_gb	Do you want to detach the selected symbol from the #1 selected style records?
:new_file_heading			:en_gb	Select file for new Raster Symbol
:style_version_dialog			:en_gb	Version Management Style Database
:default_rwo_list_label_text		:en_gb	Style records for selected RWO
:style_records_for			:en_gb	#1 style records for #2
:sym_property				:en_gb	Property
:sym_value				:en_gb	Value
:show_symbols_only?			:en_gb	Show realised symbols only?
:save_as_dialog_title			:en_gb	Enter name and location
:open_dialog_title			:en_gb	Select raster symbol configuration file
:save_as_dialog_title			:en_gb	Save As
:enter_method_name			:en_gb	Method name:
:ok					:en_gb	OK
:cancel					:en_gb	Cancel
