#% text_encoding = iso8859_1
:invalid_symbol_property	:en_gb	#3 - Invalid symbol property:
Invalid value '#2' for property '#1'
:invalid_symbol_type		:en_gb	Invalid symbol type '#2' for symbol #1
:unknown_property		:en_gb	Unknown property '#2' for symbol #1
:invalid_drawing_property	:en_gb	Property '#1' is not a valid drawing property
:inconsistent_values		:en_gb	#4 - Inconsistent Values:
Property '#1' should have a value when property '#2' has value '#3' 
:missing_parent	     	    	:en_gb  Thumbnail picture symbol - No parent symbol with name #1
:creation_error_missing_name	:en_gb	Cannot create a symbol without a name
:creation_error			:en_gb	Error creating symbol '#1' - #2
:no_suitable_stream		:en_gb	#1 - Cannot read '#2' as grid (no suitable stream)
:xml_file_does_not_exists	:en_gb	Error - xml file '#1' does not exist
:xml_read_error			:en_gb	'#1' 
:symbol_readonly		:en_gb  Operation Failed - Picture Symbol '#1' is readonly
:resource_not_in_module		:en_gb  '#1' is not a resource in a sw_module
:resource_in_use		:en_gb	Operation Failed - Picture Symbol '#1' is used by 
'#2' 
:data_file_saved		:en_gb  Configuration saved to '#1'
:xml_create_sym_error		:en_gb  #1
:duplicate_symbol_with_name	:en_gb	Error - There is already a symbol with name #1
:colourmap_reduced		:en_gb	#1
Colourmap #2 reduced to #3
:thumbnail_refresh_failed	:en_gb	Thumbnail refresh for symbol '#1' failed.
#2
:rwo_value_error		:en_gb  Object #1 raised error on value method '#2': '#3'
