#% text_encoding = iso8859_1
:activate_management_interface	:en_gb	Activate Configuration Interface
:tt_use_goto_raster_symbols	:en_gb	Use Raster Symbols on Goto?
:tt_option_sticky		:en_gb	Stay drawing Goto symbols
:tt_option_skip_invis		:en_gb	Skip drawing invisible geometries
:tt_option_use_backstop		:en_gb	Use default symbol when there is no mapping
:tt_option_no_label		:en_gb	Suppress drawing raster symbol labels
:tt_option_no_geoms		:en_gb	Suppress drawing geometries in a Goto
:tt_tick_refresh		:en_gb	Start/Stop Interval Drawing
:gui_not_loaded			:en_gb	This feature is not loaded.
:module_loaded			:en_gb	The module #1 is loaded
:load_the_gui?			:en_gb	Do you want to load the module '#1'?
(#2)
