#% text_encoding = iso8859_1
:caption	:en_gb	Raster Symbols
:sel_title	:en_gb	Select Raster Symbol
:on_off		:en_gb	Use Raster Symbols on Goto?
:sticky_goto?	:en_gb	Stay drawing Goto symbols?
:goto_skip_invisible_geoms?  :en_gb Skip drawing invisible geometries?
:use_default_for_goto?	     :en_gb Use the default symbol for every Goto?
:no_draw_labels? 	     :en_gb Suppress drawing Raster Symbol labels?
:no_draw_geoms?		     :en_gb Suppress drawing geometries in a Goto?
