pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["./mms_about.htm","About","About Version Information Prodcut name: MapMarkers Product version: 5.1.7 Document version: 5.1.7 / 3 Publish date: 11/01/2020 License The softwar...",""],
["./psyms_about.htm","About","About Version Information Product version: 5.1.7 Document version: 5.1.7 / 3 Publish date: 11/01/2020 ",""],
["./psyms_add-symbol.htm","Add symbol","Add symbol The function Add symbol allows the creation of a raster Symbol from a selected raster image file. A file dialog opens with the director...",""],
["./psyms_administration.htm","Administration","Administration The following topics are important: The modules Installation Image Magick Authorisation Load from prompt ",""],
["./psyms_api.htm","Development","Development This section describes the Magik API and and some comments on the design of Symbols. ",""],
["./psyms_authorisation.htm","Authorisation","Authorisation Manipulation of Raster Symbols is restricted to symbols other than the ones in the raster_symbols_core module. An exception is made ...",""],
["./psyms_changing-the-default-symbol.htm","Changing the default symbol","Changing the default symbol The default symbol and its properties is defined in Magik. It is created as soon as it is requested. This ensures that...",""],
["./psyms_colour.htm","Alpha Colour Editor","Alpha Colour Editor The object colour in Smallworld 5 has now a new property: alpha, a blending factor common in the raster world. The MapMarkers ...",""],
["./psyms_colourmap.htm","Colourmap","Colourmap Raster images that are processed as grids have a colourmap if the raster image is a 8bit raster or less. This colourmap can be inspected...",""],
["./psyms_configuration.htm","Configuration","Configuration There are multiple ways to customize MapMarkers. You probably will need some well designed png-files for use in your application. Th...",""],
["./psyms_creation.htm","Creation of symbols","Creation of symbols Raster symbols can be created by: 1. Loading an xml-file with raster definitions (see XML Storage ) 2. Realising raster defini...",""],
["./psyms_custom-styles.htm","Multi layered Locator Mappings","Multi layered Locator Mappings There are three different GOTO mappings: Generic Mappings When required, a symbol can be assigned to a geometry typ...",""],
["./psyms_custom-styles_2.htm","Thematics","Thematics MapMarkers can be used in thematic mapping definitions, for point geometries. Definition Interface changes: End user interface: Result: ...",""],
["./psyms_custom-symbol.htm","Auto generated draw methods","Auto generated draw methods The Configuration GUI offers an easy way to map geometries to raster symbols using a custom_draw_method. It generates,...",""],
["./psyms_default-settings-tab.htm","Default Settings Tab","Default Settings Tab The Tab Default Settings contains the list of all default settings. At the moment of writing all these values are readonly. ",""],
["./psyms_default-symbol.htm","Default Symbol","Default Symbol There is one symbol, named \"default\", that is automatically created and cannot be deleted. It acts as a backstop in several functio...",""],
["./psyms_default_settings.htm","Default Settings","Default Settings When symbols are created, and the value for some properties isn&#39;t provided, the following methods for default values are used. de...",""],
["./psyms_definitions.htm","Raster Symbol Definitions","Raster Symbol Definitions Raster Symbols can be defined in a simple prototype object. Actually a property_list. Such a Symbol Definition can be co...",""],
["./psyms_delete-symbol-(definition).htm","Delete symbol (definition)","Delete symbol (definition) The function Delete deletes the selected raster Symbol or raster Symbol definition. ",""],
["./psyms_demos.htm","Demo&#39;s","Demo&#39;s Associated Pictures 1. Start a session that contains the Related Documents from Common Office (module cs_base_model), for example Electric ...",""],
["./psyms_design-considerations.htm","Design considerations","Design considerations There are many icon packages on the internet, but you might want to develop your own. Purpose It is a good idea to envisage ...",""],
["./psyms_design.htm","Design","Design The basic object is raster_symbol, which has two subclasses: grid_raster_symbol and thumbnail_raster_symbol . The manipulation of all of th...",""],
["./psyms_development-gui.htm","Configuration GUI","Configuration GUI The Management Interface enables the creation, test and modification of symbols, mappings and styles: Click on the picture for m...",""],
["./psyms_draw-symbols.htm","Operation","Operation The Drawing Speed Monitor samples drawing speed of normal gis_style symbols and (when toggled) raster symbols. Pressing the Refresh butt...",""],
["./psyms_draw.htm","Draw","Draw The button Draw draws the selected symbol in the centre of the main window. When the option Highlight? is on, it will draw a coloured boundar...",""],
["./psyms_drawing-speed-monitor.htm","Drawing Speed Monitor","Drawing Speed Monitor To test the speed of drawing of the raster symbols, the Drawing Speed Monitor is added to the software. This module is not l...",""],
["./psyms_drawing.htm","Drawing of symbols","Drawing of symbols The major interface for drawing is putting data on the application databus. How this can be done is described here. Basic draw ...",""],
["./psyms_draw_option_toolbar.htm","Draw options toolbar","Draw options toolbar Options toolbar Stop drawing Raster Symbols on Goto actions. Draw the default symbol when no mapping is defined for geometrie...",""],
["./psyms_draw_size_mm.htm","Draw_size_mm","Draw_size_mm This property defines the width in world units of the symbol if it is drawn. The property value should be set if fixed_size? is false...",""],
["./psyms_draw_text_string_.htm","Draw_text_string?","Draw_text_string? If false, no text is drawn. ",""],
["./psyms_features.htm","Features","Features These are the major features of MapMarkers: Use of png files and full transparency The object colour in Smallworld 5 has an additional va...",""],
["./psyms_fixed-size_.htm","Fixed_size?","Fixed_size? The property fixed_size? determines if a raster symbol is drawn fixed size on the screen (value = \"Yes\"), or with a fixed width relati...",""],
["./psyms_flash-mapping.htm","Flash mapping","Flash mapping Particularly useful for value mapping with high volatile data is the Flash Mapping feature. Its execution is the responsibility of t...",""],
["./psyms_follow-selection.htm","Follow selection","Follow selection The button Follow Selection takes a graphics selection and opens and selects the geometry field in the rwo hierarchy list at the ...",""],
["./psyms_goto-mapping-tab.htm","Goto Mappings Tab","Goto Mappings Tab The Goto Mapping tab is used to create and modify Goto Mappings for three different types: Generic, Specialised and Specific. Cr...",""],
["./psyms_goto_area_style.htm","Goto_area_style","Goto_area_style The area style is used: to draw area features in a GOTO action with a mapping where \"Use?\" is true. to draw the rectangle represen...",""],
["./psyms_goto_line_style.htm","Goto_line_style","Goto_line_style The line style is used in drawing linear features in a GOTO mapping when the value use? is set to true. To edit the line style, do...",""],
["./psyms_handling-mappings.htm","Handling of mappings","Handling of mappings All mappings are stored as an instance of goto_mapping or the subclass rwo_goto_mapping, and are handled by the raster_symbol...",""],
["./psyms_highlight-text-style.htm","Highlight_text_style","Highlight_text_style The Highlight Text Style is used when a raster symbol is drawn with the parameter highlight? is true, which is done for examp...",""],
["./psyms_highlight_.htm","Highlight?","Highlight? The option Highlight? changes the Draw that is initiated by pressing the button Draw . The raster_images are not different when a symbo...",""],
["./psyms_im.htm","IM","IM Before we get to the text of the license, lets just review what the license says in simple terms: It allows you to: * freely download and use I...",""],
["./psyms_image-magick.htm","Image Magick","Image Magick MapMarkers uses ImageMagick &#174; to: 1. Create thumbnails 2. Extract Alpha channels from raster files If you have your own installation ...",""],
["./psyms_installation.htm","Installation","Installation The installation is very simple. Below are the steps for manual load. 1. Start the Module Manager 2. Select Add Product 3. Select in ...",""],
["./psyms_load-from-prompt.htm","Load from prompt","Load from prompt To evaluate the software quickly, you can load the software and open the Configuration GUI in Smallworld with: MagikSF %rs_root%/...",""],
["./psyms_mappings.htm","Geometry Mappings","Geometry Mappings For drawing of Raster Symbols as Locator for Goto operations geometry mappings can be defined. There are four types op mappings:...",""],
["./psyms_modules.htm","Modules","Modules This contents of this list is populated by the raster_symbol_handler. When a symbol is created from a module not yet in the list, the list...",""],
["./psyms_name.htm","Name","Name A raster symbol is stored by the raster_symbol_handler using a name as string. The following method returns the symbol keyed on name \"name\" o...",""],
["./psyms_new-topic.htm","Selection symbols","Selection symbols The class raster_symbol_selector (swift) enables selection if symbols. ",""],
["./psyms_operating-mode.htm","Operating Mode","Operating Mode There are two operating modes, handled by the raster_symbol_plugin. Goto draw In transient_drawer mode, the plugin handles a :goto_...",""],
["./psyms_options-panel.htm","Options Panel","Options Panel When configured (see Plugin configuration ), the following options can be set in the Smallworld Options Dialog: Changing the default...",""],
["./psyms_options.htm","Options and Configurations","Options and Configurations The following configuration options are defined: Default Picture Name Default Goto Area style Default Goto Line style H...",""],
["./psyms_organisation.htm","The modules","The modules The Raster Symbols source files are organized as bitmap resources of modules. On retrieval of resources, customisation modules are inc...",""],
["./psyms_picture-symbol-properties.htm","Symbol Properties","Symbol Properties The Symbol Property list in tab you can view and edit the properties of a raster symbol (definition). ",""],
["./psyms_picture-symbols.htm","MapMarkers","MapMarkers This software is a spin-off of a Proof of Concept for drawing normal bitmaps on the maps in Smallworld GIS. The investigation revealed ...",""],
["./psyms_pixel-offset.htm","Pixel_offset","Pixel_offset The pixel offset is the translation (in pixel space) for positioning the (raster) images &#39;drawing point&#39; in world space. The coordina...",""],
["./psyms_plugin-configuration.htm","Plugin Configuration","Plugin Configuration To embed the MapMarkers in an application, the following xml configuration is used: The folder ../modules/raster_symbols_core...",""],
["./psyms_preview-canvas.htm","Preview canvas","Preview canvas The Preview Canvas is used when a realised raster Symbol is selected. The pixels from the raster_image are mapped 1:1 to the canvas...",""],
["./psyms_processing-configuration-files.htm","Processing configuration files","Processing configuration files Configuration files are read and written by the raster_symbol_handler. Reading *cb**gis cambridge_db_open* *** The ...",""],
["./psyms_product-tests.htm","Product Tests &#38; Demos","Product Tests &#38; Demos 1. Unit tests 2. Demos ",""],
["./psyms_properties.htm","Symbol Properties","Symbol Properties In this section, the external properties of raster symbols are described: A raster_symbol has the following properties: *) Draw?...",""],
["./psyms_properties2.htm","Properties","Properties The statistics_engine has the following properties: Name Description rwo_type The rwo_type/collection name ds_name The name of the data...",""],
["./psyms_raster--grid.htm","Grid Raster Symbols","Grid Raster Symbols These are the additional external properties of a grid_raster_symbol: *) Draw? Name Default value Description grid_raster_symb...",""],
["./psyms_realise.htm","Realise","Realise The function Realise creates a raster Symbol from a selected raster Symbol definition. If successful, the raster Symbol definition will sh...",""],
["./psyms_refresh.htm","Refresh","Refresh This refreshes the Symbol (definition) list , the Symbol Property List , the Goto Mapping tab and RWO Style mapping tab . ",""],
["./psyms_retrieving-symbols.htm","Retrieving symbols","Retrieving symbols These are the basic methods for getting a raster symbol with a certain name: get_symbol() *cb**gis cambridge_db_open* get_symbo...",""],
["./psyms_route-manager.htm","Route Manager","Route Manager Sometimes a little change is enough to enhance the map. In this example the GOTO button of the route manager is modified to return a...",""],
["./psyms_rwo-style-mapping-tab.htm","RWO Style Mappings Tab","RWO Style Mappings Tab The RWO Style Mappings tab allows attachment and detachment of the standard custom draw method. See Custom Draws and Auto g...",""],
["./psyms_save-as.htm","Save As","Save As Allows to create a new configuration file. ",""],
["./psyms_save.htm","Save","Save With the button Save, the configuration is saved in an XML file. It is saved with the name raster_symbols_configuration.xml. The path is deri...",""],
["./psyms_speed.htm","Drawing speed label","Drawing speed label Shows the speed of drawing the current symbol. When a trail with multiple points is used (see Draw ), it displays the average ...",""],
["./psyms_string_selector.htm","String_selector","String_selector The property :string_selector specifies a method (or field) that should be used to get the text string that is to be drawn. The de...",""],
["./psyms_style-versions.htm","Style versions","Style versions To enable modifications to the style system, the button Versions... opens the Version Management dialog of the Style View. ",""],
["./psyms_symbol-(definition)-list.htm","Symbol (definition) list","Symbol (definition) list The Symbol (definition) list contains a list of available symbols and symbol definitions . The selected symbol is used in...",""],
["./psyms_test2.htm","Document conventions","Document conventions The following typographic conventions are used throughout the document: Arial Bold face is used for the names of menus, edito...",""],
["./psyms_text-justification.htm","Text_justification","Text_justification The position relative to the text itself. The values are identical to those of the standard positions of the Text raster Justif...",""],
["./psyms_text-picture-justification.htm","Text_raster_justification","Text_raster_justification The text_raster_justification specifies the position of the text relative to the raster. Besides the standard position v...",""],
["./psyms_text-style.htm","Text_style","Text_style These are the text_style properties in the GUI: The default text style is created as: raster_symbol.magik _pragma(classify_level=basic,...",""],
["./psyms_text_box.htm","Text_box","Text_box A bounding box in pixel space in which the text should be drawn. See text_raster_justification . ",""],
["./psyms_text_coordinate.htm","Text_coordinate","Text_coordinate The coordinate in pixel space where the text should be drawn. See text_raster_justification . ",""],
["./psyms_text_scale_factor.htm","Text_scale_factor","Text_scale_factor A scale factor to be applied to the text. This can be used for fine tuning the appearance of the text. ",""],
["./psyms_the-none-symbol.htm","The NOTHING symbol","The NOTHING symbol The raster Symbol named \"NOTHING\" can be used in GOTO mappings of geometries that should not be drawn in a Goto request. The sy...",""],
["./psyms_thumbnail-picture-symbol.htm","Thumbnail Raster Symbol","Thumbnail Raster Symbol A special kind of raster Symbol is the Thumbnail raster Symbol. It&#39;s type is :thumbnail. It is a symbol of class thumbnail...",""],
["./psyms_tools.htm","Tools","Tools These tools are not part of the software. ",""],
["./psyms_type.htm","Type","Type Either :raster, :grid or :thumbnail. (see Raster &#38; Grid ) Note that the creation of a grid type raster Symbol is rather time-consuming. It de...",""],
["./psyms_unit-tests.htm","Unit tests","Unit tests The munit tests for the raster_symbols software is organised in a separate product raster_symbols_test. To run all tests, follow the st...",""],
["./psyms_usage.htm","Usage","Usage ",""],
["./psyms_user-help.htm","User Help","User Help Depending on your configuration, the only end user interface is the Options toolbar . ",""],
["./psyms_using-statistical-engines.htm","Using statistical engines","Using statistical engines To draw values (see Value mapping ) a value scale has to be determined. This can be set manually or done automatically b...",""],
["./psyms_value-analyzer.htm","Value analyzer","Value analyzer Analyse the database and start the GUI The Field Analyser opens (this may take some while): Sort and filter if you like All fields ...",""],
["./psyms_value-mapping2.htm","Value Mapping","Value Mapping Each raster Symbol has a property value_selector. This will be used to retrieve a value from the rwo record belonging to the geometr...",""],
["./psyms_value_scale.htm","Value_scale","Value_scale The value scale is a numeric value for the scale the values are drawn. If the value scale is unset, and the raster symbol has a value_...",""],
["./psyms_value_selector.htm","Value_selector","Value_selector A value_selector is the name of a method or field that returns the value for a (numeric) property that can be mapped in a simple gr...",""],
["./psyms_warnings.htm","Warning","Warning The following warnings apply to this product. 1. To make it possible that raster symbols react on goto requests from the editor_manager, t...",""],
["./psyms_xml-configuration.htm","Configuration files","Configuration files Raster Symbols, Raster Symbol Definitions, Goto Mappings and options can be saved in an xml-file. The Management GUI has a but...",""]];
